server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.wasm$ {
        default_type application/wasm;
    }

    location ~* \.gz$ {
        add_header Content-Encoding gzip;
    }

    location ~* \.br$ {
        add_header Content-Encoding br;
    }
}
